-- Upcoming Appointments: table + RLS
-- Run this in Supabase Dashboard → SQL Editor

-- Table (snake_case for DB)
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  time text,
  type text,
  clinician_name text,
  location text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Index for listing by user and date
create index if not exists appointments_user_date_idx on public.appointments (user_id, date);

-- RLS
alter table public.appointments enable row level security;

-- Policies: users can only see/edit their own rows
create policy "Users can select own appointments"
  on public.appointments for select
  using (auth.uid() = user_id);

create policy "Users can insert own appointments"
  on public.appointments for insert
  with check (auth.uid() = user_id);

create policy "Users can update own appointments"
  on public.appointments for update
  using (auth.uid() = user_id);

create policy "Users can delete own appointments"
  on public.appointments for delete
  using (auth.uid() = user_id);

-- Optional: keep updated_at in sync
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger appointments_updated_at
  before update on public.appointments
  for each row execute function public.set_updated_at();
